import type { Metadata } from "next";
import { Inter, Lato } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/navbar";

const inter = Inter({
  subsets: ["latin"],
  weight: [
    "200",
    "300",
    "400",
    "500",
    "600",
    "700",
    "800"
  ],
  variable: "--font-inter",
});

const lato = Lato({
  subsets: ["latin"],
  weight: [
    "400",
    "700",
    "900",
  ],
  variable: "--font-lato",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
    >
      <body className={`${inter.variable} ${lato.variable}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}